services:
  moto_social_db:
    image: postgres:16-alpine
    container_name: moto_social_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - moto_social_postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - moto_social_net

  moto_social_backend:
    build:
      context: ./backend
    container_name: moto_social_backend
    restart: unless-stopped
    depends_on:
      - moto_social_db
    env_file:
      - .env
    ports:
      - '${BACKEND_PORT}:4107'
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - moto_social_net

  moto_social_frontend:
    build:
      context: ./frontend
    container_name: moto_social_frontend
    restart: unless-stopped
    depends_on:
      - moto_social_backend
    env_file:
      - .env
    ports:
      - '${FRONTEND_PORT}:3107'
    networks:
      - moto_social_net

volumes:
  moto_social_postgres_data:
    name: moto_social_postgres_data

networks:
  moto_social_net:
    name: moto_social_net
    driver: bridge
